Sprint2
ClevertecFrontendLab/sprint2-radomir-radionov pull request #1
Opened 2023-02-03 19:28 UTC by radomir-radionov

2023-02-03 19:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 70%.
Общее количество тестов: 10.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 1440px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/Test%20width%201440px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/book-page%20comment%20expand.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20after%20768px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675452703/slider%20one%20foto%20768px.png)

2023-02-03 23:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 1440px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/Test%20width%201440px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/book-page%20comment%20expand.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20after%20768px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675466527/slider%20one%20foto%20768px.png)

2023-02-04 09:20 UTC, ValadzkoAliaksei requested changes

2023-02-04 09:20 UTC, ValadzkoAliaksei commented on .editorconfig
> +root = true
удалять комментарии со скриншотами нельзя

2023-02-05 10:28 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 90%.
Общее количество тестов: 10.
Количество непройденных тестов: 1.
***
**Test width 1440px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/Test%20width%201440px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/book-page%20comment%20expand.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20after%20768px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1675592884/slider%20one%20foto%20768px.png)

2023-02-05 15:45 UTC, ValadzkoAliaksei approved these changes

2023-02-05 15:46 UTC, merged